spring.application.name=demo

spring.security.user.name=admin
spring.security.user.password=password

spring.datasource.url=jdbc:mysql://localhost:3306/securenotes
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.app.jwtSecret=mySecretKey12345678910111213141516171819202122232425262728293031323334353637383940
spring.app.jwtExpirationMs=172800000

frontend.url=http://localhost:3000